//#define S2_VIRTUAL_INHERITANCE

#define S2_SPR_DEFAULT_EDITABLE false

//#define S2_MATRIX_FIX

//#define S2_SPR_CACHE_LOCAL_MAT_SHARE
#define S2_SPR_CACHE_LOCAL_MAT_COPY

//#define S2_RES_LOG

#define S2_DISABLE_MODEL

//#define S2_SPR_TREE_DEBUG