#ifndef _SPRITE2_STAT_SYM_TYPE_H_
#define _SPRITE2_STAT_SYM_TYPE_H_

namespace s2
{

enum StatSymType
{
	STAT_SYM_IMAGE = 0,
	STAT_SYM_SCALE9,
	STAT_SYM_ICON,
	STAT_SYM_TEXTURE,
	STAT_SYM_TEXTBOX,
	STAT_SYM_COMPLEX,
	STAT_SYM_ANIMATION,
	STAT_SYM_ANIM2,
	STAT_SYM_PARTICLE3D,
	STAT_SYM_PARTICLE2D,
	STAT_SYM_SHAPE,
	STAT_SYM_MESH,
	STAT_SYM_MASK,
	STAT_SYM_TRAIL,
	STAT_SYM_SKELETON,

	STAT_SYM_MAX,

}; // StatSymType

}

#endif // _SPRITE2_STAT_SYM_TYPE_H_